version: "3.7"

services: 
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: MicroserviceUserPassword
      POSTGRES_USER: MicroserviceUser
      POSTGRES_DB: Microservice
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    
  microservice-api:
    depends_on:
      - db
    build: .
    ports:
      - "8080:80"

volumes:
  db:
    driver: local