name: Publish to NuGet

on:
  release:
    types: [published]

jobs:
  publish:
    name: Build, Pack, and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
#      - name: Build
#        run: dotnet build --configuration Release
#      - name: Test
#        run: dotnet test --configuration Release
      - name: Pack NuGets
        run: dotnet pack src/DotNetMicroserviceTemplates.csproj --configuration Release --output nupkgs
      - name: Publish to NuGet
        run: dotnet nuget push "nupkgs/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
      - name: Publish to GitHub
        run: |
          dotnet nuget add source --username kishotta --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/kishotta/index.json"
          dotnet nuget push "nupkgs/*.nupkg" --api-key ${{ secrets.PACKAGE_MANAGEMENT_PAT }} --source "github"
