name: Build and Test

on: [push]

jobs:
  build-microservice:
    name: Build and Test Microservice Template
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet restore ./src/Templates/Microservice/Microservice.Architecture.Tests/Microservice.Architecture.Tests.csproj
      - name: Build
        run: dotnet build ./src/Templates/Microservice/Microservice.Architecture.Tests/Microservice.Architecture.Tests.csproj  --configuration Release --no-restore
      - name: Test
        run: dotnet test ./src/Templates/Microservice/Microservice.Architecture.Tests/Microservice.Architecture.Tests.csproj  --no-restore
